### ISSUE TITLE
Too few arguments to function GeorgRinger\News\Hooks\Backend\RecordListQueryHook::__construct()

### ISSUE THREAD

**Issue by mweber1973** [georgringer/news#1728]
Hi,

after updating Typo3 V9 to V10 and updating news to V9.2.0 the Backend-Module throws an execption. 

Oops, an error occurred!
Too few arguments to function GeorgRinger\News\Hooks\Backend\RecordListQueryHook::__construct(), 0 passed in typo3V10/typo3_src-10.4.24/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3480 and exactly 1 expected

In my frontend the news Extension doesnt work also

Oops, an error occurred!
Too few arguments to function GeorgRinger\News\Controller\NewsController::__construct(), 0 passed in typo3V10/typo3_src-10.4.24/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3512 and exactly 4 expected

**Comment by mweber1973** [comment]
Removing / Clearing typo3temp solved this issue
