### ISSUE TITLE
Typo3 10.4.32 / news 9.0.0+ ArgumentCountError Too few arguments to function GeorgRinger\News\Controller\NewsController::__construct()

### ISSUE THREAD

**Issue by ProWebs** [georgringer/news#1862]
I got this error since upgrading news extension from 8.6.0 to 9.0.0 or higher. 

Too few arguments to function GeorgRinger\News\Controller\NewsController::__construct(), 0 passed in /var/customers/webs/klimek/typo3_src-10.4.32/typo3/sysext/core/Classes/Utility/GeneralUtility.php on line 3528 and exactly 4 expected

The error comes on all sites including news extension.
Already tried to remove all custom ts and template files and clearing cache.

**Comment by ProWebs** [comment]
Some writing permission was not given in typo3conf. Since solving this issue the error was gone.
